kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: my-python
          image: openshift/python:latest
          ports:
            - name: http
              containerPort: 4449
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-python
spec:
ports:
  - name: http-4449
    port: 4449
    protocol: TCP
    targetPort: 4449
selector:
  app: python-app
